// ui/src/components/app/SurveysPage.vue
<template>
  <div>
    <div class="flex flex-col w-full tabs">
      <div class="flex flex-col w-full items-center">
        <div class="w-full">
          <div class="overflow-x-auto">
            <table class="w-full text-sm text-left text-gray-500">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3">Name/Title</th>
                  <th scope="col" class="px-6 py-3">Build</th>
                  <th scope="col" class="px-6 py-3">Delivery</th>
                  <th scope="col" class="px-6 py-3">Share</th>
                  <th scope="col" class="px-6 py-3">Responses</th>
                  <th scope="col" class="px-6 py-3">Completion</th>
                </tr>
              </thead>
              <tbody>
                <SurveyRow 
                  v-for="survey in surveys" 
                  :key="survey.uuid" 
                  :survey="survey" 
                />
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Survey } from '@/lib/types'
import SurveyRow from './SurveyRow.vue'

interface Props {
  surveys: Survey[]
}

defineProps<Props>()
</script>

// ui_ancient/src/components/app/SurveysPage.tsx
'use client'

import { Table } from 'flowbite-react'
import { Survey } from 'lib/types'
import { SurveyRow } from './SurveyRow'

type SurveysPageProps = {
  surveys: Array<Survey>
}

export function SurveysPage({ surveys }: SurveysPageProps) {
  return (
    <div>
      <div className="flex flex-col w-full tabs">
        <div className="flex flex-col w-full items-center">
          <div className="w-full">
            <Table className="text-gray-100">
              <Table.Head>
                <Table.HeadCell>Name/Title</Table.HeadCell>
                <Table.HeadCell>Build</Table.HeadCell>
                <Table.HeadCell>Delivery</Table.HeadCell>
                <Table.HeadCell>Share</Table.HeadCell>
                <Table.HeadCell>Responses</Table.HeadCell>
                <Table.HeadCell>Completion</Table.HeadCell>
              </Table.Head>
              <Table.Body className="divide-y">
                {surveys.map((survey) => {
                  return <SurveyRow key={survey.uuid} survey={survey} />
                })}
              </Table.Body>
            </Table>
          </div>
        </div>
      </div>
    </div>
  )
}
