// ui/src/components/app/survey/SurveyQuestions.vue
<template>
  <div v-if="localSession.status === SurveySessionStatus.Completed">
    <SurveyFooter :survey="survey" />
  </div>
  <div v-else-if="!currentQuestion">
    <div class="completion-message text-center py-8">
      <h2 class="h2 text-gray-300">No more questions found in the survey.</h2>
      <div class="mt-6">
        <button 
          @click="tryAgain"
          class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          Try again
        </button>
      </div>
    </div>
  </div>
  <div v-else-if="currentQuestion">
    <div class="question-container">
      <h2 class="h2 text-gray-300">{{ currentQuestion.label }}</h2>
      <p v-if="currentQuestion.description" class="text-gray-300 mb-6">{{ currentQuestion.description }}</p>
      
      <!-- Single Choice -->
      <div v-if="currentQuestion.type === SurveyQuestionType.SingleChoice" class="space-y-3">
        <div v-for="option in currentQuestion.options" :key="option" class="flex items-center">
          <input 
            type="radio" 
            :id="option" 
            :name="currentQuestion.uuid"
            :value="option"
            v-model="answerValue"
            class="mr-3 text-blue-600 focus:ring-blue-500"
          />
          <label :for="option" class="text-gray-300">{{ option }}</label>
        </div>
      </div>

      <!-- Multiple Choice -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.MultipleChoice" class="space-y-3">
        <div v-for="option in currentQuestion.options" :key="option" class="flex items-center">
          <input 
            type="checkbox" 
            :id="option" 
            :value="option"
            v-model="answerValue"
            class="mr-3 text-blue-600 focus:ring-blue-500 rounded"
          />
          <label :for="option" class="text-gray-300">{{ option }}</label>
        </div>
      </div>

      <!-- Short Text -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.ShortText">
        <input 
          type="text"
          v-model="answerValue"
          class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
        />
      </div>

      <!-- Long Text -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.LongText">
        <textarea 
          v-model="answerValue"
          class="w-full p-3 border border-gray-300 rounded-lg h-32 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
        ></textarea>
      </div>

      <!-- Email -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.Email">
        <input 
          type="email"
          v-model="answerValue"
          class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
        />
      </div>

      <!-- Date -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.Date">
        <input 
          type="date"
          v-model="answerValue"
          class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
        />
      </div>

      <!-- Yes/No -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.YesNo" class="space-y-3">
        <div class="flex items-center">
          <input 
            type="radio" 
            id="yes" 
            name="yesno"
            value="true"
            v-model="answerValue"
            class="mr-3 text-blue-600 focus:ring-blue-500"
          />
          <label for="yes" class="text-gray-300">Yes</label>
        </div>
        <div class="flex items-center">
          <input 
            type="radio" 
            id="no" 
            name="yesno"
            value="false"
            v-model="answerValue"
            class="mr-3 text-blue-600 focus:ring-blue-500"
          />
          <label for="no" class="text-gray-300">No</label>
        </div>
      </div>

      <!-- Rating -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.Rating" class="flex items-center space-x-2">
        <span v-for="i in (currentQuestion.max || 5)" :key="i" class="cursor-pointer text-2xl select-none">
          <Icon 
            icon="heroicons:star-solid"
            :class="[i <= Number(answerValue) ? 'text-yellow-400' : 'text-gray-300']"
            @click="answerValue = i.toString()"
          />
        </span>
      </div>

      <!-- Ranking -->
      <div v-else-if="currentQuestion.type === SurveyQuestionType.Ranking" class="space-y-4">
        <p class="text-gray-300 text-sm">Drag and drop items below to rank them.</p>
        <div class="space-y-2">
          <div 
            v-for="(item, index) in sortableItems" 
            :key="item.id"
            draggable="true"
            @dragstart="onDragStart(index)"
            @dragover.prevent
            @drop="onDrop(index)"
            @dragenter.prevent
            class="flex items-center p-3 bg-gray-100 border border-gray-300 rounded-lg cursor-move hover:bg-gray-200 transition-colors"
            :class="{ 'opacity-50': draggedIndex === index }"
          >
            <Icon icon="heroicons:bars-3" class="w-5 h-5 text-gray-500 mr-3" />
            <span class="text-gray-900">{{ item.name }}</span>
          </div>
        </div>
      </div>

      <div class="mt-6 flex gap-3">
        <button 
          v-if="prevQuestion"
          @click="goToPrev"
          class="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 flex items-center gap-2"
        >
          <Icon icon="heroicons:arrow-left" class="w-4 h-4" />
          Previous
        </button>
        <button 
          @click="submitAnswer"
          class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          :disabled="!canSubmit"
        >
          {{ nextQuestion ? 'Next' : 'Complete' }}
          <Icon icon="heroicons:arrow-right" class="w-4 h-4" />
        </button>
      </div>

      <ErrCode v-if="errMessage" :message="errMessage" class="mt-4" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { Icon } from '@iconify/vue'
import {
  SurveyQuestionType,
  SurveySessionStatus,
} from '@/lib/types'
import type {
  Survey,
  SurveySession,
  SurveyQuestion,
} from '@/lib/types'
import { submitQuestionAnswer } from '@/lib/api'
import ErrCode from '@/components/ui/ErrCode.vue'
import SurveyFooter from './SurveyFooter.vue'
import {
  determineNextQuestion,
  determinePrevQuestionWithAnswer,
  determineInitialQuestion,
} from '@/lib/questions'

interface Props {
  survey: Survey
  session: SurveySession
}

interface SortableItem {
  id: number
  name: string
}

const props = defineProps<Props>()

const initialQuestion = determineInitialQuestion(props.survey, props.session)
const currentQuestion = ref<SurveyQuestion | undefined>(initialQuestion)
const answerValue = ref<string | string[]>('')
const sortableItems = ref<SortableItem[]>([])
const draggedIndex = ref<number | null>(null)
const errMessage = ref<string>('')
const localSession = ref<SurveySession>({ 
  ...props.session,
  question_answers: props.session?.question_answers || []
})

const nextQuestion = computed(() => {
  if (!currentQuestion.value) return undefined
  return determineNextQuestion(props.survey, localSession.value, currentQuestion.value)
})

const prevQuestion = computed(() => {
  if (!currentQuestion.value) return undefined
  return determinePrevQuestionWithAnswer(props.survey, localSession.value, currentQuestion.value)
})

const canSubmit = computed(() => {
  if (!currentQuestion.value) return false
  
  if (currentQuestion.value.type === SurveyQuestionType.Ranking) {
    return sortableItems.value.length > 0
  }
  
  return !!answerValue.value
})

// Drag and drop functions
function onDragStart(index: number) {
  draggedIndex.value = index
}

function onDrop(dropIndex: number) {
  if (draggedIndex.value === null || draggedIndex.value === dropIndex) return
  
  const draggedItem = sortableItems.value[draggedIndex.value]
  sortableItems.value.splice(draggedIndex.value, 1)
  sortableItems.value.splice(dropIndex, 0, draggedItem)
  
  draggedIndex.value = null
}

// Initialize answer value from existing answer
watch(currentQuestion, (newQuestion) => {
  if (!newQuestion) return

  if (newQuestion.type === SurveyQuestionType.Ranking) {
    // Initialize sortable items for ranking questions
    if (newQuestion.answer?.value) {
      const rankingArray = newQuestion.answer.value as string[]
      sortableItems.value = rankingArray.map((item, index) => ({
        id: index,
        name: item
      }))
    } else {
      sortableItems.value = newQuestion.options.map((option, index) => ({
        id: index,
        name: option
      }))
    }
    answerValue.value = []
  } else if (newQuestion.answer?.value !== undefined) {
    const value = newQuestion.answer.value
    if (Array.isArray(value)) {
      answerValue.value = value.map(v => String(v))
    } else {
      answerValue.value = String(value)
    }
  } else {
    if (newQuestion.type === SurveyQuestionType.MultipleChoice) {
      answerValue.value = []
    } else {
      answerValue.value = ''
    }
  }
}, { immediate: true })

async function submitAnswer() {
  if (!currentQuestion.value) return

  errMessage.value = ''
  
  // Convert answer value based on question type
  let processedValue = answerValue.value
  if (currentQuestion.value.type === SurveyQuestionType.Rating) {
    processedValue = Number(answerValue.value)
  } else if (currentQuestion.value.type === SurveyQuestionType.YesNo) {
    processedValue = answerValue.value === 'true'
  } else if (currentQuestion.value.type === SurveyQuestionType.Ranking) {
    processedValue = sortableItems.value.map(item => item.name)
  }
  
  const payload = {
    value: processedValue
  }

  const res = await submitQuestionAnswer(
    props.survey.url_slug,
    localSession.value.uuid,
    currentQuestion.value.uuid,
    payload
  )

  if (res.error) {
    // Check if we have detailed error information
    if (res.data && res.data.error_details) {
      errMessage.value = res.data.error_details
    } else {
      errMessage.value = res.error
    }
    return
  }

  // Update local session with new answer
  if (!localSession.value || !localSession.value.question_answers) {
    console.error('localSession or question_answers is null')
    return
  }
  
  const existingAnswerIndex = localSession.value.question_answers.findIndex(
    (a) => a.question_uuid === currentQuestion.value!.uuid
  )

  if (existingAnswerIndex >= 0) {
    localSession.value.question_answers[existingAnswerIndex] = {
      question_id: currentQuestion.value.id,
      question_uuid: currentQuestion.value.uuid,
      answer: { value: processedValue }
    }
  } else {
    localSession.value.question_answers.push({
      question_id: currentQuestion.value.id,
      question_uuid: currentQuestion.value.uuid,
      answer: { value: processedValue }
    })
  }

  // Move to next question or complete
  const next = nextQuestion.value
  if (next) {
    currentQuestion.value = next
  } else {
    // Mark as completed - this should trigger the thank you page
    console.log('Survey completed, setting status to completed')
    localSession.value.status = SurveySessionStatus.Completed
    localStorage.removeItem(`survey_session_id:${props.survey.url_slug}`)
  }
}

function goToPrev() {
  const prev = prevQuestion.value
  if (prev) {
    currentQuestion.value = prev
  }
}

function tryAgain() {
  localStorage.removeItem(`survey_session_id:${props.survey.url_slug}`)
  window.location.reload()
}
</script>

<style scoped>
/* Drag and drop styling handled via Tailwind classes in template */
</style>

// ui/src/components/app/survey/SurveyQuestions.tsx
'use client'

import { useState } from 'react'
import {
  Survey,
  SurveySession,
  SurveyQuestion,
  SurveyQuestionType,
  SurveySessionStatus,
} from 'lib/types'
import {
  Dropdown,
  Button,
  Checkbox,
  TextInput,
  Textarea,
  Datepicker,
} from 'flowbite-react'
import { HiArrowSmRight, HiSelector } from 'react-icons/hi'
import { ErrCode } from 'components/ui/ErrCode'
import { submitQuestionAnswer } from 'lib/api'
import { ReactSortable } from 'react-sortablejs'
import moment from 'moment'
import { DatepicketTheme } from 'components/ui/themes'
import SurveyFooter from './SurveyFooter'
import {
  determineNextQuestion,
  determinePrevQuestionWithAnswer,
  determineNextQuestionWithAnswer,
  determineInitialQuestion,
} from 'lib/questions'

type SurveyQuestionsProps = {
  survey: Survey
  session: SurveySession
  apiURL: string
}

interface SortableItemType {
  id: number
  name: string
}

export default function SurveyQuestions({
  survey,
  session,
  apiURL,
}: SurveyQuestionsProps) {
  const initialQuestion = determineInitialQuestion(survey, session)

  const [currentQuestion, setCurrentQuestion] = useState<
    SurveyQuestion | undefined
  >(initialQuestion)
  const [surveySession, setSurveySession] = useState<SurveySession>(session)

  const [errorMsg, setErrorMsg] = useState<string | undefined>(undefined)
  const [isNextLoading, setIsNextLoading] = useState<boolean>(false)

  // values state
  const [selectedStringValue, setSelectedStringValue] = useState<
    string | undefined
  >(undefined)
  const [selectedArrayValue, setSelectedArrayValue] = useState<string[]>([])
  const [sortableItems, setSortableItems] = useState<SortableItemType[]>([])

  if (surveySession.status === SurveySessionStatus.Completed) {
    return (
      <div className="outro">
        <h1
          className="h2"
          dangerouslySetInnerHTML={{
            __html: survey.config.outro
              ? survey.config.outro.replace(/(?:\r\n|\r|\n)/g, '<br>')
              : 'Response submitted.<br />Thank you!',
          }}
        ></h1>
      </div>
    )
  }

  if (!currentQuestion) {
    return (
      <div className="outro">
        <h1 className="h2">No more questions found in the survey.</h1>

        <div className="flex flex-col py-8 lg:py-16 items-center text-center">
          <Button
            className="try-again"
            onClick={async () => {
              localStorage.removeItem(`survey_session_id:${survey.url_slug}`)
              window.location.reload()
            }}
          >
            Try again
          </Button>
        </div>
      </div>
    )
  }

  const prev = determinePrevQuestionWithAnswer(
    survey,
    surveySession,
    currentQuestion
  )
  const next = determineNextQuestionWithAnswer(
    survey,
    surveySession,
    currentQuestion
  )
  const questionsCount = survey.config.questions.questions.length

  let questionContent = <></>
  switch (currentQuestion.type) {
    case SurveyQuestionType.SingleChoice:
      questionContent = (
        <div className="dropdown">
          <Dropdown
            label={
              selectedStringValue !== undefined
                ? selectedStringValue
                : 'Select one option from the list'
            }
          >
            {currentQuestion.options.map((option, index) => (
              <Dropdown.Item
                key={index}
                onClick={() => {
                  setSelectedStringValue(option)
                }}
              >
                {option}
              </Dropdown.Item>
            ))}
          </Dropdown>
        </div>
      )
      break
    case SurveyQuestionType.MultipleChoice:
      questionContent = (
        <div className="dropdown">
          <Dropdown
            dismissOnClick={false}
            label={
              selectedArrayValue.length > 0
                ? selectedArrayValue.join(', ')
                : 'Select multiple options from the list'
            }
          >
            {currentQuestion.options.map((option, index) => (
              <Dropdown.Item
                key={index}
                onClick={() => {
                  if (selectedArrayValue.includes(option)) {
                    setSelectedArrayValue(
                      selectedArrayValue.filter((v) => v !== option)
                    )
                  } else {
                    setSelectedArrayValue([...selectedArrayValue, option])
                  }
                }}
              >
                <Checkbox
                  className="checkbox"
                  checked={selectedArrayValue.includes(option)}
                />
                &nbsp;
                {option}
              </Dropdown.Item>
            ))}
          </Dropdown>
        </div>
      )
      break
    case SurveyQuestionType.ShortText:
      questionContent = (
        <TextInput
          defaultValue={selectedStringValue || ''}
          placeholder="Type your answer here..."
          required
          onChange={(e) => {
            const newValue = e.target.value === '' ? undefined : e.target.value
            setSelectedStringValue(newValue)
          }}
        />
      )
      break
    case SurveyQuestionType.EmailText:
      questionContent = (
        <TextInput
          defaultValue={selectedStringValue || ''}
          placeholder="Type your email here..."
          required
          type='email'
          onChange={(e) => {
            const newValue = e.target.value === '' ? undefined : e.target.value
            setSelectedStringValue(newValue)
          }}
        />
      )
      break
    case SurveyQuestionType.LongText:
      questionContent = (
        <Textarea
          defaultValue={selectedStringValue || ''}
          placeholder="Type your answer here..."
          required
          onChange={(e) => {
            const newValue = e.target.value === '' ? undefined : e.target.value
            setSelectedStringValue(newValue)
          }}
        />
      )
      break
    case SurveyQuestionType.Date:
      questionContent = (
        <Datepicker
          className="datepicker"
          theme={DatepicketTheme}
          placeholder="Select the date..."
          defaultDate={
            selectedStringValue ? new Date(selectedStringValue) : new Date()
          }
          value={selectedStringValue || ''}
          showClearButton={false}
          onSelectedDateChanged={(date) => {
            setSelectedStringValue(moment(date).format('YYYY-MM-DD'))
          }}
        />
      )
      break
    case SurveyQuestionType.Rating:
      const numbers = []
      if (currentQuestion.max && currentQuestion.min) {
        for (let i = currentQuestion.min; i <= currentQuestion.max; i++) {
          numbers.push(i)
        }
      }
      questionContent = (
        <Button.Group>
          {numbers.map((number) => {
            const isSelected =
              selectedStringValue !== undefined &&
              number.toString() === selectedStringValue

            return (
              <Button
                key={number}
                className={isSelected ? 'rating-selected' : 'rating'}
                onClick={() => {
                  setSelectedStringValue(number.toString())
                }}
              >
                {number}
              </Button>
            )
          })}
        </Button.Group>
      )
      break
    case SurveyQuestionType.Ranking:
      if (sortableItems.length === 0) {
        setSortableItems(
          currentQuestion.options.map((option, index) => {
            return {
              id: index,
              name: option,
            }
          })
        )
      }

      questionContent = (
        <>
          <p className="caption">Drag and drop items below to rank them.</p>
          <ReactSortable list={sortableItems} setList={setSortableItems}>
            {sortableItems.map((item) => (
              <div key={item.id} className="sortable-item">
                <HiSelector className="inline" />
                &nbsp;
                {item.name}
              </div>
            ))}
          </ReactSortable>
        </>
      )
      break
    case SurveyQuestionType.YesNo:
      questionContent = (
        <Button.Group>
          <Button
            key={'yes'}
            className={
              selectedStringValue === 'yes' ? 'rating-selected' : 'rating'
            }
            onClick={() => {
              setSelectedStringValue('yes')
            }}
          >
            Yes
          </Button>
          <Button
            key={'no'}
            className={
              selectedStringValue === 'no' ? 'rating-selected' : 'rating'
            }
            onClick={() => {
              setSelectedStringValue('no')
            }}
          >
            No
          </Button>
        </Button.Group>
      )
      break
  }

  async function submitAnswer() {
    if (currentQuestion === undefined) {
      return
    }

    setIsNextLoading(true)

    let payload = {}
    switch (currentQuestion.type) {
      case SurveyQuestionType.SingleChoice:
      case SurveyQuestionType.ShortText:
      case SurveyQuestionType.LongText:
      case SurveyQuestionType.EmailText:
      case SurveyQuestionType.Date:
        payload = {
          value: selectedStringValue,
        }
        break
      case SurveyQuestionType.MultipleChoice:
        payload = {
          value: selectedArrayValue,
        }
        break
      case SurveyQuestionType.Rating:
        payload = {
          value: parseInt(selectedStringValue as string),
        }
        break
      case SurveyQuestionType.Ranking:
        payload = {
          value: sortableItems.map((item) => item.name),
        }
        break
      case SurveyQuestionType.YesNo:
        payload = {
          value: selectedStringValue === 'yes',
        }
        break
    }

    const apiRes = await submitQuestionAnswer(
      survey.url_slug,
      session.uuid,
      currentQuestion.uuid,
      payload,
      apiURL
    )

    if (apiRes.error) {
      setErrorMsg(apiRes.data.error_details || apiRes.error)
    } else {
      const newSession = apiRes.data.data as SurveySession
      setSurveySession(newSession)
      resetValues()

      const nextQuestion = determineNextQuestion(
        survey,
        newSession,
        currentQuestion
      )
      setCurrentQuestion(nextQuestion)
      if (nextQuestion && nextQuestion.answer !== undefined) {
        fillQuestion(nextQuestion)
      }
    }

    setIsNextLoading(false)
  }

  function resetValues() {
    setSelectedStringValue(undefined)
    setSelectedArrayValue([])
    setSortableItems([])
    setErrorMsg(undefined)
  }

  function fillQuestion(question: SurveyQuestion) {
    switch (question.type) {
      case SurveyQuestionType.SingleChoice:
      case SurveyQuestionType.ShortText:
      case SurveyQuestionType.LongText:
      case SurveyQuestionType.Date:
        setSelectedStringValue(question.answer.value as string)
        break
      case SurveyQuestionType.MultipleChoice:
        setSelectedArrayValue(question.answer.value as string[])
        break
      case SurveyQuestionType.Rating:
        const ratingInt = question.answer.value as number
        setSelectedStringValue(ratingInt.toString())
        break
      case SurveyQuestionType.Ranking:
        const rankingArray = question.answer.value as string[]
        setSortableItems(
          rankingArray.map((item, index) => {
            return {
              id: index,
              name: item,
            }
          })
        )
        break
      case SurveyQuestionType.YesNo:
        const yesNoBool = question.answer.value as boolean
        setSelectedStringValue(yesNoBool ? 'yes' : 'no')
        break
    }
  }

  const isSubmitDisabled =
    selectedStringValue === undefined &&
    selectedArrayValue.length === 0 &&
    sortableItems.length === 0

  return (
    <>
      <div className="mb-auto flex-grow">
        <div className="mx-auto max-w-screen-md text-center py-8 lg:py-24 gap-4">
          <p className="h4 py-8">{currentQuestion.label}</p>
          {currentQuestion.description && (
            <p className="caption">{currentQuestion.description}</p>
          )}
          <form className="form">{questionContent}</form>
          <div className="w-full flex justify-center mt-8">
            <Button
              className="next-question"
              disabled={isSubmitDisabled}
              isProcessing={isNextLoading}
              onClick={async () => {
                await submitAnswer()
              }}
            >
              Next&nbsp;
              <HiArrowSmRight className="inline" />
            </Button>
          </div>
          {errorMsg && (
            <div className="w-full flex justify-center mt-8">
              <ErrCode message={errorMsg} />
            </div>
          )}
        </div>
      </div>

      <SurveyFooter
        current={currentQuestion.index + 1}
        size={questionsCount}
        canGoBack={prev !== undefined}
        canGoForward={next !== undefined}
        onBackClick={() => {
          if (prev) {
            resetValues()
            setCurrentQuestion(prev)
            fillQuestion(prev)
          }
        }}
        onForwardClick={() => {
          if (next) {
            resetValues()
            setCurrentQuestion(next)
            fillQuestion(next)
          }
        }}
      />
    </>
  )
}
