// ui/src/components/app/survey/SurveyIntro.vue
<template>
  <div v-if="surveySession !== undefined">
    <SurveyQuestions :survey="survey" :session="surveySession" />
  </div>
  <div v-else class="intro">
    <h1 class="h1">{{ config.title }}</h1>
    <p class="intro-title" v-html="formatIntro(config.intro)"></p>
    <div class="intro-start">
      <button 
        class="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
        @click="startSurvey"
      >
        Start
      </button>
    </div>
    <div v-if="errMessage" class="flex flex-col py-8 px-8">
      <ErrCode :message="errMessage" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Survey, SurveyConfig, SurveySession } from '@/lib/types'
import { createSurveySession } from '@/lib/api'
import ErrCode from '@/components/ui/ErrCode.vue'
import SurveyQuestions from './SurveyQuestions.vue'

interface Props {
  survey: Survey
}

const props = defineProps<Props>()

const errMessage = ref<string | undefined>(undefined)
const surveySession = ref<SurveySession | undefined>(undefined)

const config = computed(() => props.survey.config as SurveyConfig)

function formatIntro(intro: string): string {
  return intro.replace(/(?:\r\n|\r|\n)/g, '<br>')
}

async function startSurvey() {
  errMessage.value = undefined
  const sessionRes = await createSurveySession(props.survey.url_slug)
  if (sessionRes.error) {
    errMessage.value = sessionRes.error
    return
  }

  localStorage.setItem(
    `survey_session_id:${props.survey.url_slug}`,
    sessionRes.data.data.uuid
  )
  surveySession.value = sessionRes.data.data
}
</script>

// ui/src/components/app/survey/SurveyIntro.tsx
'use client'

import { useState } from 'react'
import { Survey, SurveyConfig, SurveySession } from 'lib/types'
import { Button } from 'flowbite-react'
import { ErrCode } from 'components/ui/ErrCode'
import SurveyQuestions from 'components/app/survey/SurveyQuestions'
import { createSurveySession } from 'lib/api'

type SurveyIntroProps = {
  survey: Survey
}

export default function SurveyIntro({ survey }: SurveyIntroProps) {
  const [errMessage, seterrMessage] = useState<string | undefined>(undefined)
  const [surveySession, setSurveySession] = useState<SurveySession | undefined>(
    undefined
  )
  const config = survey.config as SurveyConfig

  if (surveySession !== undefined) {
    return (
      <SurveyQuestions
        survey={survey}
        session={surveySession as SurveySession}
      />
    )
  }

  return (
    <div className="intro">
      <h1 className="h1">{config.title}</h1>
      <p
        className="intro-title"
        dangerouslySetInnerHTML={{
          __html: config.intro.replace(/(?:\r\n|\r|\n)/g, '<br>'),
        }}
      ></p>
      <div className="intro-start">
        <Button
          onClick={async () => {
            seterrMessage(undefined)
            const sessionRes = await createSurveySession(survey.url_slug)
            if (sessionRes.error) {
              seterrMessage(sessionRes.error)
              return
            }

            localStorage.setItem(
              `survey_session_id:${survey.url_slug}`,
              sessionRes.data.data.uuid
            )
            setSurveySession(sessionRes.data.data)
          }}
        >
          Start
        </Button>
      </div>
      {errMessage && (
        <div className="flex flex-col py-8 px-8">
          <ErrCode message={errMessage} />
        </div>
      )}
    </div>
  )
}
