// ui/src/components/app/survey/SurveyLayout.tsx
'use client'

import { BgPattern } from 'components/ui/BgPattern'
import { SurveyThemeCustom } from 'lib/types'
import { ReactNode } from 'react'
import 'styles/survey/default.css'

type SurveyLayoutProps = {
  children?: ReactNode
  urlSlug?: string
  surveyTheme?: string
  apiURL?: string
}

export default function SurveyLayout({
  children,
  urlSlug,
  surveyTheme,
  apiURL,
}: SurveyLayoutProps) {
  return (
    <main className="flex flex-col h-screen">
      {surveyTheme == SurveyThemeCustom && (
        <link rel="stylesheet" href={apiURL + '/surveys/' + urlSlug + '/css'} />
      )}
      <BgPattern />
      {children}
    </main>
  )
}

// ui/src/components/app/survey/SurveyLayout.vue
<template>
  <main class="flex flex-col h-screen">
    <link 
      v-if="surveyTheme === SurveyThemeCustom" 
      rel="stylesheet" 
      :href="`${API_BASE_URL}/surveys/${urlSlug}/css`" 
    />
    <BgPattern />
    <slot />
  </main>
</template>

<script setup lang="ts">
import BgPattern from '@/components/ui/BgPattern.vue'
import { SurveyThemeCustom } from '@/lib/types'

interface Props {
  urlSlug?: string
  surveyTheme?: string
}

withDefaults(defineProps<Props>(), {
  urlSlug: '',
  surveyTheme: ''
})

const API_BASE_URL = import.meta.env.VITE_API_ADDR || 'http://localhost:9900'
</script>
