// ui/src/components/app/survey/SurveyForm.tsx
'use client'

import { useEffect, useState } from 'react'
import { Survey, SurveySession } from 'lib/types'
import { getSurveySession } from 'lib/api'
import SurveyIntro from 'components/app/survey/SurveyIntro'
import SurveyQuestions from 'components/app/survey/SurveyQuestions'

type SurveyFormProps = {
  survey: Survey
}

export default function SurveyForm({ survey }: SurveyFormProps) {
  const [surveySession, setSurveySession] = useState<SurveySession | undefined>(
    undefined
  )
  const [isNewSession, setIsNewSession] = useState<boolean>(true)
  const [isLoading, setIsLoading] = useState<boolean>(true)
  useEffect(() => {
    ;(async () => {
      if (typeof window !== 'undefined') {
        const lsValue = localStorage.getItem(
          `survey_session_id:${survey.url_slug}`
        )

        if (!lsValue) {
          setIsNewSession(true)
          setIsLoading(false)
          return
        }

        const sessionRes = await getSurveySession(
          window.location.hostname,
          survey.url_slug,
          lsValue
        )
        if (sessionRes.error || !sessionRes.data.data) {
          localStorage.removeItem(`survey_session_id:${survey.url_slug}`)
          setIsNewSession(true)
          setIsLoading(false)
          return
        }

        setSurveySession(sessionRes.data.data)
        setIsNewSession(false)
        setIsLoading(false)
      }
    })()
  }, [survey])

  if (isLoading) {
    return (
      <div className="mx-auto text-center py-16">
        <div role="status">
          <svg
            aria-hidden="true"
            className="spinner"
            viewBox="0 0 100 101"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
              fill="currentColor"
            />
            <path
              d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
              fill="currentFill"
            />
          </svg>
        </div>
      </div>
    )
  }

  if (isNewSession) {
    return <SurveyIntro survey={survey} />
  }

  return (
    <SurveyQuestions survey={survey} session={surveySession as SurveySession} />
  )
}

// ui/src/components/app/survey/SurveyForm.vue
<template>
  <div v-if="isLoading" class="mx-auto text-center py-16">
    <div role="status">
      <Icon icon="svg-spinners:180-ring-with-bg" class="w-8 h-8 text-blue-600 mx-auto" />
    </div>
  </div>
  <div v-else-if="isNewSession">
    <SurveyIntro :survey="survey" />
  </div>
  <div v-else>
    <SurveyQuestions :survey="survey" :session="surveySession!" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Icon } from '@iconify/vue'
import type { Survey, SurveySession } from '@/lib/types'
import { getSurveySession } from '@/lib/api'
import SurveyIntro from './SurveyIntro.vue'
import SurveyQuestions from './SurveyQuestions.vue'

interface Props {
  survey: Survey
}

const props = defineProps<Props>()

const surveySession = ref<SurveySession | undefined>(undefined)
const isNewSession = ref<boolean>(true)
const isLoading = ref<boolean>(true)

onMounted(async () => {
  if (typeof window !== 'undefined') {
    const lsValue = localStorage.getItem(
      `survey_session_id:${props.survey.url_slug}`
    )

    if (!lsValue) {
      isNewSession.value = true
      isLoading.value = false
      return
    }

    const sessionRes = await getSurveySession(props.survey.url_slug, lsValue)
    if (sessionRes.error || !sessionRes.data.data) {
      localStorage.removeItem(`survey_session_id:${props.survey.url_slug}`)
      isNewSession.value = true
      isLoading.value = false
      return
    }

    surveySession.value = sessionRes.data.data
    isNewSession.value = false
    isLoading.value = false
  }
})
</script>
